FROM microsoft/aspnet:4.7.1-windowsservercore-ltsc2016

RUN iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1')) ;choco install -y --no-progress nodejs-lts git python2
RUN npm -g install pm2
EXPOSE 4000 8000
