FROM microsoft/aspnet

RUN iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1')) ;choco install -y --no-progress nodejs-lts git
RUN npm -g install pm2
COPY start.ps1 c:/
ENTRYPOINT c:/start.ps1
EXPOSE 3000 8000
