---
- name: Revert Initial State
  hosts: hyperv
  tasks:
  - debug:
      msg: "Revert"

  - win_shell: get-VM CRMApi | Restore-VMSnapshot -Name InitialState -Confirm:$false

  - win_shell: Get-VM CRMApi | Start-VM
 
  - win_shell: Start-Sleep -s 30



- name: Install CRMApi
  hosts: CRMApi
  roles:
          - CRMApi
          - CRMAuth

