---
- name: Revert Initial State
  hosts: hyperv
  vars:
          ar_code: "TEST"
          api_url: "10.1.8.155:8080/api"
  tasks:
  - debug:
      msg: "Revert CRMGui to Initial State"

  - win_shell: get-VM CRMGui | Restore-VMSnapshot -Name InitialState -Confirm:$false

  - win_shell: Get-VM CRMGui | Start-VM
 
  - win_shell: Start-Sleep -s 30



- name: Install CRMGui
  hosts: CRMGui
  roles:
          - CRMGui


