---
- name: Revert Initial State
  hosts: hyperv
  tasks:
  - debug:
      msg: "Revert CRMGui to Initial State"

  - win_shell: get-VM RabbitMQQueue | Restore-VMSnapshot -Name InitialState -Confirm:$false

  - win_shell: Get-VM RabbitMQQueue | Start-VM
 
  - win_shell: Start-Sleep -s 30



- name: Configure RabbitMQ Queue
  hosts: RabbitMQQueue
  roles:
          - RabbitMQQueue


