---
version: '3.3'
services:
        post_db:
          image: mongo:latest
          volumes:
            - post_db:/data/db
          networks:
                  reddit:
                          aliases:
                                  - post_db
                                  - comment_db
        ui:
          image: angelok139/ui:latest
          ports:
            - 9292:9292/tcp
          networks:
            - reddit

        post:
          image: angelok139/post:latest
          networks:
            - reddit

        comment:
          image: angelok139/comment:latest
          networks:
            - reddit

        cadvisor:
          image: google/cadvisor:latest
          volumes:
                - '/:/rootfs:ro'
                - '/var/run:/var/run:rw'
                - '/sys:/sys:ro'
                - '/var/lib/docker:/var/lib/docker:ro'
          ports:
                - '8080:8080'
          networks:
                - reddit 
        grafana:
          image: grafana/grafana
          volumes:
                - grafana_data:/var/lib/grafana
          environment:
                - GF_SECURITY_ADMIN_USER=admin
                - GF_SECURITY_ADMIN_PASSWORD=secret
          depends_on:
            - prometheus
          ports:
            - 3000:3000
          networks:
            - reddit
   
        prometheus:
          image: angelok139/prometheus:latest
          ports:
            - 9090:9090/tcp
          networks:
            - reddit

        node-exporter:
          image: prom/node-exporter:latest
          user: root
          volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
          command:
                - '--path.procfs=/host/proc'
                - '--path.sysfs=/host/sys'
                - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'          
          networks:
                - reddit

volumes: 
    post_db:

    grafana_data:

networks:
    reddit:
