---
# Preset:
# MSSQL Server 2016
#

- name: Install software
  hosts: all
  tasks:
    - name: Install WebPI
      win_chocolatey:
              name: webpicmd
              state: present

    - name: Install 7-zip
      win_chocolatey:
              name: 7zip
              state: present

    - name: Install IIS part 1
      win_feature:
              name: Web-Http-Redirect,Web-Custom-Logging,Web-Log-Libraries,Web-Request-Monitor,Web-Http-Tracing,Web-Dyn-Compression,Web-IP-Security,Web-Url-Auth,Web-CertProvider,Web-Static-Content
              state: present
              include_sub_features: True
              include_management_tools: True
    - name: Install IIS part 2
      win_feature:
              name: Web-Basic-Auth,Web-ASP,Web-Asp-Net,Web-Asp-Net45,Web-ISAPI-Ext,Web-Net-Ext,Web-Net-Ext45,Web-ISAPI-Filter,Web-Mgmt-Service,Server-Media-Foundation,NET-WCF-HTTP-Activation45,NET-WCF-TCP-Activation45,Web-CGI
              state: present
              include_sub_features: True
              include_management_tools: true



    - name: Install PHP
      win_webpicmd:
              name: "PHP56"

    - name: Copy configuration file
      win_template:
              src: php.ini.j2
              dest: "C:\\Program Files (x86)\\PHP\\v5.6\\php.ini"

    - name: Upload ncftp
      win_copy:
        src: files/NcFTP.msi
        dest: c:\temp\

    - name: Install ncftp
      win_package: 
        path: c:\temp\NcFTP.msi
        state: present


    - name: Copy Install script
      win_template:
              src: files/InstallScript.ps1.j2
              dest: c:\InstallScript.ps1

    - name: Run Install Script
      win_command: powershell c:\InstallScript.ps1
      register: install_out
    
    - name: Print result of install_out
      debug:
        var: install_out

    - name: Copy configuration file cbasicglobal.php
      win_template:
              src: cbasicglobal.php.j2
              dest: "C:\\inetpub\\wwwroot\\CbookingWebsite\\include\\cbasicglobal.php"
    
    - name: Copy configuration file Backofficecbasicglobal.php
      win_template:
              src: backoffice_cbasicglobal.php.j2
              dest: "C:\\inetpub\\wwwroot\\BackOffice\\include\\cbasicglobal.php"
        
    - name: Copy configuration file Web.config for cbooking.ru
      win_template:
              src: cbooking_web_config.j2
              dest: "C:\\inetpub\\wwwroot\\CbookingWebsite\\Web.config"

    - name: Copy configuration file Web.config for hdsgatewaylite
      win_template:
              src: hdsgatewaylite_web_config.j2
              dest: "C:\\inetpub\\Applications\\hdsgatewaylite\\Web.config"

    - name: Copy configuration file Web.config for hdswebapi
      win_template:
              src: hdswebapi_web_config.j2
              dest: "C:\\inetpub\\Applications\\hdswebapi\\Web.config"

    - name: Copy configuration file Web.config for ast.cbooking.ru
      win_template:
              src: ast_web_config.j2
              dest: "C:\\inetpub\\wwwroot\\ast.cbooking.ru\\Web.config"
              
    - name: Copy configuration file Web.config for hdsorderfo
      win_template:
              src: hdsorderfo_web_config.j2
              dest: "C:\\inetpub\\Applications\\hdsorderfo\\Web.config"

    - name: Copy configuration file web.config for hdsgateway
      win_template:
              src: hdsgateway_web_config.j2
              dest: "C:\\inetpub\\Applications\\hdsgateway\\web.config"

    - name: Copy configuration file web.config for hdscontent
      win_template:
              src: hdscontent_web_config.j2
              dest: "C:\\inetpub\\Applications\\hdscontent\\web.config"

    - name: Copy configuration file Web.config for hdswebsite
      win_template:
              src: hdswebsite_web_config.j2
              dest: "C:\\inetpub\\Applications\\hdswebsite\\Web.config"
    
    - name: Copy configuration file Web.config for DBExporter
      win_template:
              src: dbexporter.j2
              dest: "C:\\Program Files\\DBExporter\\DBExporterConsole.exe.config"

    - name: Copy configuration file for VBRunningService
      win_template:
              src: VBRunningServiceSQL.j2
              dest: "C:\\Program Files (x86)\\Vitus Bering\\VbRunningServiceSQL\\bin\\Release\\VBRunningServiceSQL.exe.config"

    - name: Remove Default web Site
      win_iis_website:
        name: "Default Web Site"
        state: absent

    - name: Configure AppPool
      win_iis_webapppool:
        name: appPool
        state: started
        attributes:
                managedPipelineMode: Classic
                startMode: AlwaysRunning
                enable32BitAppOnWin64: True

    - name: Configure Backoffice apppool
      win_iis_webapppool:
        name: BackOffice
        state: started
        attributes:
                managedPipelineMode: Classic
                startMode: AlwaysRunning
                enable32BitAppOnWin64: False

    - name: Create CBooking WebSite
      win_iis_website:
        name: "CBooking Core"
        port: 80
        application_pool: "appPool"
        physical_path: C:\inetpub\wwwroot\CbookingWebsite
        state: started

    - name: Create ast.absolute_url
      win_iis_website:
        name: "ast.cbooking.ru"
        port: 80
        hostname: "ast.{{absolute_url}}"
        application_pool: "DefaultAppPool"
        physical_path: C:\inetpub\wwwroot\ast.cbooking.ru
        state: started

    - name: Create ast.absolute_url
      win_iis_website:
        name: "Backoffice"
        port: 85
        application_pool: "BackOffice"
        physical_path: C:\inetpub\wwwroot\BackOffice
        state: started

    - name: Create Applications
      win_iis_webapplication:
        name: "{{ item }}"
        site: "CBooking Core"
        application_pool: "appPool"
        state: present
        physical_path: "C:\\inetpub\\Applications\\{{ item }}"
      with_items:
        - hdscontent
        - buhdocs
        - channelmanagerapi
        - cmxmlapi
        - download
        - hdsbo
        - hdscontent
        - hdsgateway
        - hdsorderfo
        - hdsorderfo2
        - hdssvc
        - hdswebsite
        - hotelgateway
        - hdsgatewaylite
        - hdswebapi

    - name: Create firewall rule for CBooking website
      win_firewall_rule:
              name: CBooking Site
              localport: 80
              action: allow
              direction: in
              protocol: tcp
              state: present
              enabled: yes

    - name: Create firewall rule for backoffice
      win_firewall_rule:
              name: Backoffice
              localport: 85
              action: allow
              direction: in
              protocol: tcp
              state: present
              enabled: yes

    - name: Add user for Office Interop
      win_user:
              name: interopuser
              password: "{{ InteropUserPassword }}"
              password_never_expires: yes
              state: present

    - name: Install service for VBRunningService
      win_service:
              name: VBRunningService
              path: "C:\\Program Files (x86)\\Vitus Bering\\VbRunningServiceSQL\\bin\\Release\\VBRunningServiceSQL.exe"
              start_mode: auto
              state: started

    - name: Start IIS
      win_service:
              name: W3SVC
              state: started
              
