---
# tasks file for CRMApi

    - name: Install Applications
      win_chocolatey:
              name: '{{ item }}'
              state: present
              proxy_url: "http://proxy.sirena-travel.ru:3128"
      with_items:
      - 7zip
      - rabbitmq
    
    - name: Copy Install script
      win_template:
              src: InstallScript.ps1.j2
              dest: c:\InstallScript.ps1

    - name: Run Install Script
      win_shell: c:\InstallScript.ps1

    - name: Change user for LeoTicketSH service
      win_service:
              name: Leo.Ticket.SH
              username: LocalSystem
              password: ""
              state: started 

    - name: Create firewall rule for LeoTicketSH
      win_firewall_rule:
              name: LeoTicketSH
              localport: 8086
              action: allow
              direction: in
              protocol: tcp
              state: present
              enabled: yes

