---
# tasks file for CRMGui

    - name: Install 7-zip
      win_chocolatey:
              name: '{{ item }}'
              state: present
              proxy_url: "http://proxy.sirena-travel.ru:3128"
      with_items:
      - 7zip
    
    - name: Copy Install script
      win_template:
              src: InstallScript.ps1.j2
              dest: c:\InstallScript.ps1

    - name: Run Install Script
      win_shell: c:\InstallScript.ps1

    - name: Install IIS part 1
      win_feature:
              name: Web-Http-Redirect,Web-Custom-Logging,Web-Log-Libraries,Web-Request-Monitor,Web-Http-Tracing,Web-Dyn-Compression,Web-IP-Security,Web-Url-Auth,Web-CertProvider,Web-Static-Content
              state: present
              include_sub_features: True
              include_management_tools: True
      tags:   install_iis
    - name: Install IIS part 2
      win_feature:
              name: Web-Basic-Auth,Web-ASP,Web-Asp-Net,Web-Asp-Net45,Web-ISAPI-Ext,Web-Net-Ext,Web-Net-Ext45,Web-ISAPI-Filter,Web-Mgmt-Service,Server-Media-Foundation,NET-WCF-HTTP-Activation45,NET-WCF-TCP-Activation45
              state: present
              include_sub_features: True
              include_management_tools: true
      tags:   install_iis
    - name: Allow Firewall for Apps
      win_firewall_rule:
              name: Site
              localport: 8080
              action: allow
              direction: in
              protocol: tcp
              state: present
              enabled: yes

    - name: Create GUI site
      win_iis_website:
        name: "GUIDev"
        port: 8080
        physical_path: "c:\\projects\\Crm.Gui.Dev"
        state: started

    - name: Add config to GUI
      win_template:
              src: config.UT.json.j2
              dest: c:\projects\Crm.Gui.Dev\utadmin\assets\config.json

    - name: Add config to GUI
      win_template:
              src: config.SAdmin.json.j2
              dest: c:\projects\Crm.Gui.Dev\sadmin\assets\config.json


