---
  - name: Install ruby and rubygames and required packages
    apt: "name={{ item }} state=present"
    with_items:
      - ruby-full
      - ruby-dev
      - build-essential
      - git

  - name: Install Ruby bundler
    gem:
      name: bundler
      state: present
      user_install: no

