---
- name: Deploy new app
  hosts: app
  become: yes

  tasks:
  - name: Fetch latest Distr
    git:
            repo: 'https://github.com/Artemmkin/reddit.git'
            dest: /usr/share/reddit
            version: monolith
            force: yes
    notify: reload puma

  - name: Bundle install
    bundler:
            state: present
            chdir: /usr/share/reddit


  handlers:
  - name: reload puma
    systemd:
            name: pumad
            daemon_reload: yes
            state: restarted

