---
- name: Configure hosts & deploy
  hosts: all
  vars:
          mongo_bind_ip: 0.0.0.0
          db_host: 10.132.0.2
          
  tasks:
  - name: Change mongo config file
    become: true
    template:
           src: templates/mongod.conf.j2
           dest: /etc/mongod.conf
           mode: 0644
    tags: db-tag
    notify: restart mongod
  
  - name: Fetch latest Distr
    become: yes
    git:
            repo: 'https://github.com/Artemmkin/reddit.git'
            dest: /usr/share/reddit
            version: monolith
            force: yes
    tags: deploy-tag
    notify: reload puma

  - name: Bundle install
    become: yes
    bundler:
            state: present
            chdir: /usr/share/reddit
    tags: deploy-tag

  - name: Add unit file for Puma
    become: true
    copy:
            src: files/pumad.service
            dest: /etc/systemd/system/pumad.service
    tags: app-tag
    notify: reload puma

  - name: Add config for DB connection
    template:
            src: templates/db_config.j2
            dest: /home/avih/db_config
    tags: app-tag

  - name: enable puma
    become: true
    systemd:
             name: pumad
             enabled: yes
    tags: app-tag


  handlers:
  - name: restart mongod
    become: true
    service:
            name: mongod
            state: restarted

  - name: reload puma
    become: true
    systemd:
            name: pumad
            daemon_reload: yes
            state: restarted
