# Setup ruby
- name: "Reddit App: Configure app enviropment"
  hosts: reddit_app
  gather_facts: no
  become: yes

  tasks:
  - name: Install ruby and rubygames and required packages
    apt: "name={{ item }} state=present"
    with_items:
      - ruby-full
      - ruby-dev
      - build-essential

  - name: Install Ruby bundler
    gem:
      name: bundler
      state: present
      user_install: no

# Setup and configure mongodb for reddit app
- name: "Reddit App: Install mongodb"
  hosts: reddit_db
  gather_facts: no
  become: yes
  
  tasks:
  
  - name: Install mongodb
    yum: "name=mongodb-server state=present"
    
  - name: Enable MongoDB server  
    service: "name=mongod enabled=yes state=started"
  

# Deploy reddit app
- name: "Reddit App: Deploy application"
  hosts: reddit_app
  gather_facts: no
  become: yes

  tasks:
  - name: Get App from git
    git: "repo=https://github.com/Artemmkin/reddit.git dest=/usr/share/reddit"

  - name: Install app bundles
    bundler: "state=present gemfile=/usr/share/reddit/Gemfile"

  - name: Copy service file
    copy: "src=/home/avih/repo/angelok139/AutoDeploy.scripts/pumad.service dest=/etc/systemd/system/pumad.service"

    #  - name: Add ServerIP
    # raw: echo "export SERVER_IP=104.155.21.139" >>/etc/bash.bashrc

  - name: Enable PumaD
    service: "name=pumad enabled=yes state=started"

