Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |v|
    v.memory = 512
  end

  config.vm.define "dbserver" do |db|
    db.vm.provision "ansible" do |ansible|
      ansible.playbook = "site.yml"
      ansible.groups = {
      "db" => ["dbserver"],
      "db:vars" => {"mongo_bind_ip" => "0.0.0.0" }
      }
    end 
    db.vm.box = "centos/7"
    db.vm.hostname = "dbserver"
    db.vm.network :private_network, ip: "10.10.10.10"
  end
  
  config.vm.define "appserver" do |app|
    app.vm.provision "ansible" do |ansible|
      ansible.playbook = "site.yml"
      ansible.groups = {
      "app" => ["appserver"],
      "app:vars" => { "db_host" => "10.10.10.10" }
      }
      ansible.extra_vars = { 
	 "deploy_user" => "ubuntu"
      }
    
    end
    app.vm.box = "ubuntu/xenial64"
    app.vm.hostname = "appserver"
    app.vm.network :private_network, ip: "10.10.10.20"
  end
end

