---
# tasks file for RabbitMQQueue
- name: Install RabbitMQ
  become: yes
  yum:
          name: rabbitmq-server
          state: latest

- name: Copy config for RabbitMQ
  become: yes
  copy:
          src: templates/rabbitmq.config
          dest: /etc/rabbitmq/rabbitmq.config

- name: Start RabbitMQ
  become: yes
  systemd:
          name: rabbitmq-server
          enabled: yes
          state: started
- name: Enable ports in firewall
  become: yes
  firewalld:
          port: 5671-5672/tcp
          state: enabled

- name: Create vhost
  become: yes
  rabbitmq_vhost:
          name: /utpnr
          state: present

- name: Create user utpublisher
  become: yes
  rabbitmq_user:
          user: utpublisher
          password: testpass
          permissions:
                  - vhost: /utpnr
                    configure_priv: .*
                    read_priv: .*
                    write_priv: .*
          state: present

- name: Create user consumer
  become: yes
  rabbitmq_user:
          user: utconsumer
          password: testpass
          permissions:
                  - vhost: /utpnr
                    configure_priv: .*
                    read_priv: .*
                    write_priv: .*
          state: present
- name: Create Queue
  become: yes
  shell: rabbitmqctl set_permissions -p /utpnr utpublisher "rabbitmq_ut_import_test" ".*" "" && rabbitmqctl set_permissions -p /utpnr utconsumer "rabbitmq_ut_import_test" "" ".*"


