---
# tasks file for RabbitMQQueue
- name: Install RabbitMQ
  become: yes
  yum:
          name: rabbitmq-server
          state: latest

- name: Copy config for RabbitMQ
  become: yes
  copy:
          src: templates/rabbitmq.config
          dest: /etc/rabbitmq/rabbitmq.config

- name: Start RabbitMQ
  become: yes
  systemd:
          name: rabbitmq-server
          enabled: yes
          state: started
- name: Enable ports in firewall
  become: yes
  firewalld:
          port: 5671-5672/tcp
          state: enabled
          permanent: true


