---
# tasks file for RabbitMQQueue
- name: Install RabbitMQ
  become: yes
  yum:
          name: rabbitmq-server
          state: latest

- name: Copy config for RabbitMQ
  become: yes
  copy:
          src: templates/rabbitmq.config
          dest: /etc/rabbitmq/rabbitmq.config

- name: Start RabbitMQ
  become: yes
  systemd:
          name: rabbitmq-server
          enabled: yes
          state: started
- name: Enable ports in firewall
  become: yes
  firewalld:
          port: 5671-5672/tcp
          state: enabled
          permanent: true
- name: Create vhost
  become: yes
  rabbitmq_vhost:
          name: /utpnr
          state: present

- name: Create user
  become: yes
  rabbitmq_user:
          user: rmqtest
          password: rmqpass
          permissions:
                  - vhost: /utpnr
                    configure_priv: .*
                    read_priv: .*
                    write_priv: .*
          state: present


